dev:
  less:
    lessCompress: false
    lessYuiCompress: false
    lessCleanCss: false
    lessOptimization: 2
  uglify:
    mangle: false
    drop_console: false
    beautify: true
    preserveCommments: true
    compress: false
release:
  less:
      lessCompress: true
      lessYuiCompress: true
      lessCleanCss: true
      lessOptimization: 2
  uglify:
    mangle: true
    drop_console: true
    beautify: false
    preserveCommments: false
    compress: true
