# -------------------------------------------------------------------
# General Settings
# -------------------------------------------------------------------
general:
  # Path to the extension directory in Qlik Sense Desktop
  LocalExtensionPath:   "<%= localExtensionDir %>"

  # Name of the Extension as defined in the generator
  ExtensionName:        "<%= extensionName %>"

  # Name of the Extension, safe to be used for file-names
  ExtensionNameSafe:    "<%= extensionNameSafe %>"

  # Namespace
  ExtensionNamespace:   "<%= extensionNamespace %>"

  # Description of the Extension as defined in the generator
  ExtensionDescription: "<%= extensionDescription %>"

  # Version of the extension, will be re-used in several areas,
  # e.g the generated .zip-file in the 'release' Grunt-task
  Version:              "0.0.1"

# -------------------------------------------------------------------
# Settings for the 'dev' Grunt task
# -------------------------------------------------------------------
dev:
  less: # Documentation: https://github.com/gruntjs/grunt-contrib-less
    lessCompress: false
    lessYuiCompress: false
    lessCleanCss: false
    lessOptimization: 2
  uglify: # Documentation: https://github.com/gruntjs/grunt-contrib-uglify
    mangle: false
    drop_console: false
    beautify: true
    preserveCommments: true
    compress: false

# -------------------------------------------------------------------
# Settings for the 'release' Grunt task
# -------------------------------------------------------------------
release:
  less: # Documentation: https://github.com/gruntjs/grunt-contrib-less
    lessCompress: true
    lessYuiCompress: true
    lessCleanCss: true
    lessOptimization: 2
  uglify: # Documentation: https://github.com/gruntjs/grunt-contrib-uglify
    mangle: true
    drop_console: true
    beautify: false
    preserveCommments: false
    compress: true
